### ISSUE TITLE
specify port name separate from host

### ISSUE THREAD

**Issue by adobeDan** [adobe/frl-online-proxy#18]
**Is your feature request related to a problem? Please describe.**
The `--ssl` command-line mode flag is really handy for running with and without SSL, but in fact I don't want both SSL and non-SSL connections being made to the same port, because I want to run two copies of the proxy off the same config file and different flags.  So please allow specifying the port number separately from the host, and also have two different port specifications: one used for SSL and one used for non-SSL connections.

**Describe the solution you'd like**
See above: one port specification for use with SSL, and a different port specification for use with non-SSL.  Only one host specification, done separately from the two port specifications.

**Describe alternatives you've considered**
Anything else requires me to have two different configs, which is a pain because they have to be kept in sync.

**Additional context**
This would also workaround the problem we have where you can't type a ':' on Windows keyboards. :)

**Comment by adorton-adobe** [comment]
I can take this

**Comment by adorton-adobe** [comment]
I've implemented this at https://github.com/adorton-adobe/frl-online-proxy/tree/feature/standalone-port

It's a branch of `import-export` so I'll wait until #17 is merged before submitting the PR.

Instead of specifying a port option for plain and another for secure, I just implemented one port option that can be overridden from a command-line option. The rationale is you can fairly easily spin up another proxy by changing the `--port` option.

```
# defaults: port (8443), ssl enabled
$ ./frl-proxy start

# start a plain proxy on a different port
$ ./frl-proxy start --ssl false --port 8080
```

Let me know if you think this is sufficient or if we need plain and secure port options.

**Comment by adobeDan** [comment]
Not my favorite plan to start adding back in more command-line options but I can live with it :)

**Comment by adorton-adobe** [comment]
No harm in evaluating both approaches. Here's what I think that would look like - https://github.com/adorton-adobe/frl-online-proxy/tree/feature/standalone-port-2

Let me know what you think.

**Comment by adobeDan** [comment]
I definitely like the one with two port specifications better.  That way the default config is all set up to run either way with minimal fuss.  (One suggestion: use 8080 rather than 8000 for the default http port.)

**Comment by adorton-adobe** [comment]
Sounds good. Once we get #17 merged, I'll create PR for this.
